import { Injectable } from '@angular/core';
import { Meetings } from '../models/meetings.model';

@Injectable({
  providedIn: 'root',
})
export class MeetingsService {
  constructor() {}
  getData() {
    return MEETINGS_DATA;
  }
}

const MEETINGS_DATA: Meetings[] = [
  {
    id: 1,
    date: '2022-11-07',
    startTime: '18:00',
    finishTime: '19:30',
    title: 'Spotkanie organizacyjne z koordynatorem przedmiotu',
    description: '(omówienie regulaminu przedmiotu, utworzenie zespołów)',
    isMeetingWithCoordinator: true,
    location: 'WMiI UMK (sala S9)',
  },
  {
    id: 2,
    date: '2022-11-14',
    startTime: '16:00',
    finishTime: '16:45',
    title: 'Spotkanie z opiekunem zespołu',
    description: '(omówienie zasad zaliczenia, sprawy organizacyjne)',
    isMeetingWithCoordinator: false,
    location: 'WMiI UMK (sala L14)',
  },
  {
    id: 3,
    date: '2022-11-22',
    startTime: '18:00',
    finishTime: '19:00',
    title: 'Spotkanie z opiekunem zespołu',
    description: '(przedstawienie kilku propozycji aplikacji)',
    isMeetingWithCoordinator: false,
    location: 'WMiI UMK (sala L14)',
  },
  {
    id: 4,
    date: '2022-12-06',
    startTime: '18:00',
    finishTime: '19:30',
    title: 'Spotkanie z opiekunem zespołu',
    description: '(przedstawienie kilku propozycji aplikacji)',
    isMeetingWithCoordinator: false,
    location: 'WMiI UMK (sala L14)',
  },
  {
    id: 5,
    date: '2022-12-20',
    startTime: '16:00',
    finishTime: '16:45',
    title: 'Spotkanie z opiekunem zespołu',
    description: '(ocena możliwości realizacji projektu)',
    isMeetingWithCoordinator: false,
    location: 'WMiI UMK (sala L14)',
  },
  {
    id: 6,
    date: '2023-01-10',
    startTime: '16:00',
    finishTime: '16:50',
    title: 'Spotkanie z opiekunem zespołu',
    description:
      '(dyskusja na temat struktury projektu, rozpoczęcie pisania aplikacji)',
    isMeetingWithCoordinator: false,
    location: 'WMiI UMK (sala L14)',
  },
  {
    id: 7,
    date: '2023-01-17',
    startTime: '16:15',
    finishTime: '17:00',
    title: 'Spotkanie z opiekunem zespołu',
    description: '(dyskusja nad rodzajem licencji)',
    isMeetingWithCoordinator: false,
    location: 'WMiI UMK (sala L14)',
  },
  {
    id: 8,
    date: '2023-01-24',
    startTime: '16:15',
    finishTime: '17:15',
    title: 'Spotkanie z opiekunem zespołu',
    description: '(rozmowa o dalszym rozwoju aplikacji)',
    isMeetingWithCoordinator: false,
    location: 'WMiI UMK (sala L14)',
  },
  {
    id: 9,
    date: '2023-01-31',
    startTime: '16:15',
    finishTime: '16:45',
    title: 'Spotkanie z opiekunem zespołu',
    description: '(rozmowa na temat raportów semestralnych)',
    isMeetingWithCoordinator: false,
    location: 'WMiI UMK (sala L14)',
  },
  {
    id: 10,
    date: '2023-02-07',
    startTime: '16:15',
    finishTime: '16:25',
    title: 'Spotkanie z opiekunem zespołu',
    description: '(podsumowanie tygodniowej pracy zespołu)',
    isMeetingWithCoordinator: false,
    location: 'WMiI UMK (sala L14)',
  },
  {
    id: 11,
    date: '2023-02-08',
    startTime: '18:30',
    finishTime: '19:00',
    title: 'Spotkanie kontrolne z koordynatorem przedmiotu',
    description:
      '(podsumowanie pracy zespołu, rozmowa o dalszym rozwoju projektu)',
    isMeetingWithCoordinator: true,
    location: 'zdalnie',
  },
  {
    id: 12,
    date: '2023-02-14',
    startTime: '16:15',
    finishTime: '16:25',
    title: 'Spotkanie z opiekunem zespołu',
    description: '(dyskusja na temat poprawek na stronie)',
    isMeetingWithCoordinator: false,
    location: 'WMiI UMK (sala L14)',
  },
  {
    id: 13,
    date: '2023-02-21',
    startTime: '16:15',
    finishTime: '16:40',
    title: 'Spotkanie z opiekunem zespołu',
    description: '(rozmowa o postępach zespołu w aplikacji)',
    isMeetingWithCoordinator: false,
    location: 'zdalnie',
  },
  {
    id: 14,
    date: '2023-03-07',
    startTime: '16:00',
    finishTime: '16:45',
    title: 'Spotkanie z opiekunem zespołu',
    description:
      '(ustalenie terminu spotkań, rozmowa o organizacji pracy - GitHub)',
    isMeetingWithCoordinator: false,
    location: 'WMiI UMK (sala L14)',
  },
  {
    id: 15,
    date: '2023-03-08',
    startTime: '18:00',
    finishTime: '18:20',
    title: 'Spotkanie z opiekunem zespołu',
    description: '(rozmowa na temat prezentacji projektów)',
    isMeetingWithCoordinator: false,
    location: 'WMiI UMK (sala L12)',
  },
  {
    id: 16,
    date: '2023-03-15',
    startTime: '18:00',
    finishTime: '18:25',
    title: 'Spotkanie z opiekunem zespołu',
    description:
      '(wykonanie zdjęć członków zespołu, rozmowa o dalszym rozwoju aplikacji)',
    isMeetingWithCoordinator: false,
    location: 'WMiI UMK (sala L12)',
  },
  {
    id: 17,
    date: '2023-03-22',
    startTime: '17:45',
    finishTime: '17:55',
    title: 'Spotkanie z opiekunem zespołu',
    description: '(dyskusja nad przebiegiem pracy zespołu)',
    isMeetingWithCoordinator: false,
    location: 'WMiI UMK (sala L12)',
  },
  {
    id: 18,
    date: '2023-03-29',
    startTime: '18:00',
    finishTime: '18:35',
    title: 'Spotkanie z opiekunem zespołu',
    description: '(dyskusja nad przebiegiem pracy zespołu)',
    isMeetingWithCoordinator: false,
    location: 'WMiI UMK (sala L12)',
  },
  {
    id: 19,
    date: '2023-04-12',
    startTime: '18:00',
    finishTime: '18:10',
    title: 'Spotkanie z opiekunem zespołu',
    description: '(dyskusja nad przebiegiem pracy zespołu)',
    isMeetingWithCoordinator: false,
    location: 'WMiI UMK (sala L12)',
  },
  {
    id: 20,
    date: '2023-04-19',
    startTime: '17:45',
    finishTime: '18:10',
    title: 'Spotkanie z opiekunem zespołu',
    description:
      '(przedstawienie działania aplikacji, omówienie następnych zadań)',
    isMeetingWithCoordinator: false,
    location: 'WMiI UMK (sala L12)',
  },
  {
    id: 21,
    date: '2023-04-26',
    startTime: '17:45',
    finishTime: '18:00',
    title: 'Spotkanie z opiekunem zespołu',
    description: '(podsumowanie tygodniowej pracy zespołu)',
    isMeetingWithCoordinator: false,
    location: 'WMiI UMK (sala L12)',
  },
  {
    id: 22,
    date: '2023-05-11',
    startTime: '16:00',
    finishTime: '17:50',
    title: 'Spotkanie z opiekunem zespołu',
    description: '(rozmowa o prezentacji, podsumowanie pracy zespołu)',
    isMeetingWithCoordinator: false,
    location: 'zdalnie',
  },
  {
    id: 23,
    date: '2023-05-18',
    startTime: '16:00',
    finishTime: '18:00',
    title: 'Spotkanie z opiekunem zespołu',
    description: '(podsumowanie pracy zespołu)',
    isMeetingWithCoordinator: false,
    location: 'zdalnie',
  },
  {
    id: 25,
    date: '2023-05-25',
    startTime: '16:00',
    finishTime: '17:00',
    title: 'Spotkanie z opiekunem zespołu',
    description: '(omówienie przygotowania prezentacji)',
    isMeetingWithCoordinator: false,
    location: 'zdalnie',
  },
];
